@AggregatorApi_HostAddress = https://localhost:7187
# your actual token here
@jwt_token = 

###
# Get JWT token (anonymous)
GET {{AggregatorApi_HostAddress}}/Authentication
Accept: application/json

###
# Get aggregated data (requires JWT)
GET {{AggregatorApi_HostAddress}}/Aggregate
Authorization: Bearer {{jwt_token}}
Accept: application/json

###
# Get statistics (requires JWT)
GET {{AggregatorApi_HostAddress}}/Statistics
Authorization: Bearer {{jwt_token}}
Accept: application/json
